eservices:
  - type: cron
    name: agendador_execucao 
    schedule: "*/5 * * * *"
    runtime: python
    buildCommand: ""
    startCommand: "python3 entregas_business_gratuito.py && python3 entregas_plastic_gratuito.py && python3 entregas_recovery_gratuito.py"
