eservices:
  - type: cron
    name: agendador_execucao 
    schedule: "*/5 * * * *"
    runtime: python
    buildCommand: ""
    startCommand: "entregas_business_gratuito.py", "entregas_plastic_gratuito.py", "entregas_recovery_gratuito.py"
